import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/ui";
import { Providers } from "./providers";

export const poppins = Poppins({
  weight: ["400", "600", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Screens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-base-400`}>
        <Providers>
          <Header />
          <div className="m-auto min-h-screen max-w-[1540px]">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
